theme: jekyll-theme-hydure

plugins:
  - jekyll-remote-theme

remote_theme: zivong/jekyll-theme-hydure

title: moka

author.name: moka
author.url: mokaim.github.io

# Ruby Date Format
date_format: "%B %-d, %Y"

permalink: /:year-:month-:day-:title/

